name: Test Typesetting with Existing Actions
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on:  ubuntu-18.04
    container: docker://konn/texlive2020-slim:20201227.3

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: tex-cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ./.latex
          # An explicit key for restoring and saving the cache
          key: ${{github.ref}}-${{ runner.os }}
          restore-keys: |
            ${{github.ref}}-
            master-
      - name: Creates .latex directory if missing
        if: steps.tex-cache.outeputs.cache-hit != 'true'
        run: "mkdir ./.latex"

      - name: Typeset it
        run: |
          cluttex --output-directory=$(pwd)/.latex -e lualatex main.tex

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: main.pdf
          path: main.pdf
          if-no-files-found: error # optional, default is warn
          retention-days: 90
