name: Test Typesetting with Existing Actions
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on:  ubuntu-18.04
    container: docker://konn/texlive2020-slim:20201227.4

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: tex-cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            main.fdb_latexmk
            .latex/
            
          # An explicit key for restoring and saving the cache
          key: ${{github.ref}}-${{ runner.os }}-${{ hashFiles('**/*.tex', '**/*.sty', '**/*.fdb_latexmk') }}
          restore-keys: |
            ${{github.ref}}-${{ runner.os }}-
            ${{github.ref}}-
            master-
      - name: Create .latex directory if missing
        if: steps.tex-cache.outputs.cache-hit != 'true'
        run: mkdir -p .latex
      - name: Restore latex files
        if: steps.tex-cache.outputs.cache-hit == 'true'
        run: |
          find .latex/ -maxdepth 1 -maxdepth 1 | read && cp -r .latex/* . || echo "No .latex/ directory found. skip"
      - name: Typeset it
        run: |
          latexmk -pdflua main.tex
      
      - name: Store latex generated files
        run: |
          for fdb in $(find . -name "*.fdb_latexmk"); do
              for i in $(cat $fdb | texlua ./extract-generateds.lua); do
                echo "cp $(dirname $fdb)/$i .latex/$(dirname $fdb)/$i"
                cp $(dirname $fdb)/$i .latex/$(dirname $fdb)/$i
              done
          done

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: main.pdf
          path: main.pdf
          if-no-files-found: error # optional, default is warn
          retention-days: 90
