name: Test Typesetting with Existing Actions
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on:  ubuntu-18.04

    steps:
      - name: Typeset it
        uses: vinay0410/tectonic-action@v1.1.2
        with:
          tex_path: main.tex
          push: false

